spring:
  liquibase:
    change-log: db/changelog/changeLog.xml
  datasource:
    driverClassName: org.postgresql.Driver


auth.service.jwt:
  secret: "test"
  issuer: "test.com"
  accessExpirationTime: 1800000
  refreshExpirationTime: 2592000000